/**
 * Notification Types for Role-Based System
 * Defines all notification types and their metadata structure
 */

export enum NotificationType {
  // ============ STUDENT NOTIFICATIONS ============
  EXAM_SCHEDULED = "EXAM_SCHEDULED",
  EXAM_STARTING_SOON = "EXAM_STARTING_SOON",
  EXAM_COMPLETED = "EXAM_COMPLETED",
  EXAM_RESULT_PUBLISHED = "EXAM_RESULT_PUBLISHED",
  EXAM_ATTEMPT_FLAGGED = "EXAM_ATTEMPT_FLAGGED",
  PROGRESS_MILESTONE = "PROGRESS_MILESTONE",
  DEADLINE_REMINDER = "DEADLINE_REMINDER",
  NEW_SUBJECT_ENROLLED = "NEW_SUBJECT_ENROLLED",
  LOW_PERFORMANCE_ALERT = "LOW_PERFORMANCE_ALERT",
  DIFFICULTY_LEVEL_UNLOCK = "DIFFICULTY_LEVEL_UNLOCK",
  ACCOUNT_APPROVED = "ACCOUNT_APPROVED",
  EXAM_NOTIFICATION = "EXAM_NOTIFICATION",
  EXAM_ANNOUNCEMENT = "EXAM_ANNOUNCEMENT",

  // ============ FACULTY NOTIFICATIONS ============
  EXAM_CREATED = "EXAM_CREATED",
  EXAM_PUBLISHED = "EXAM_PUBLISHED",
  EXAM_STARTED = "EXAM_STARTED",
  EXAM_COMPLETED_FACULTY = "EXAM_COMPLETED_FACULTY",
  STUDENT_SUBMISSION_RECEIVED = "STUDENT_SUBMISSION_RECEIVED",
  VIOLATION_DETECTED = "VIOLATION_DETECTED",
  QUESTION_BATCH_IMPORTED = "QUESTION_BATCH_IMPORTED",
  EXAM_PERFORMANCE_SUMMARY = "EXAM_PERFORMANCE_SUMMARY",
  NEW_QUESTION_IMPORT_REQUEST = "NEW_QUESTION_IMPORT_REQUEST",
  STUDENT_PERFORMANCE_ALERT = "STUDENT_PERFORMANCE_ALERT",

  // ============ ADMIN NOTIFICATIONS ============
  SYSTEM_ALERT = "SYSTEM_ALERT",
  USER_ACCOUNT_CREATED = "USER_ACCOUNT_CREATED",
  USER_ACCOUNT_STATUS_CHANGED = "USER_ACCOUNT_STATUS_CHANGED",
  EXAM_VIOLATION_ESCALATION = "EXAM_VIOLATION_ESCALATION",
  BULK_IMPORT_COMPLETED = "BULK_IMPORT_COMPLETED",
  SYSTEM_ERROR_LOGGED = "SYSTEM_ERROR_LOGGED",
  SUSPICIOUS_ACTIVITY_DETECTED = "SUSPICIOUS_ACTIVITY_DETECTED",
  DATABASE_BACKUP_COMPLETED = "DATABASE_BACKUP_COMPLETED",
  SECURITY_ALERT = "SECURITY_ALERT",
  USER_APPROVAL_REQUIRED = "USER_APPROVAL_REQUIRED",
  PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST",
}

export interface NotificationMetadata {
  examId?: number;
  studentId?: number;
  facultyId?: number;
  score?: number;
  passingScore?: number;
  subject?: string;
  difficulty?: string;
  timestamp?: Date;
  violationType?: string;
  severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  actionUrl?: string;
  [key: string]: any;
}

export interface NotificationPayload {
  type: NotificationType;
  title: string;
  message: string;
  metadata?: NotificationMetadata;
  priority?: "LOW" | "MEDIUM" | "HIGH";
}
