export const VIOLATION_SEVERITY = {
  TAB_SWITCH: "WARNING",
  WINDOW_BLUR: "WARNING",
  FULLSCREEN_EXIT: "ERROR",
  COPY_ATTEMPT: "ERROR",
  PASTE_ATTEMPT: "ERROR",
  MULTIPLE_FACE_DETECTED: "ERROR",
  NO_FACE_DETECTED: "WARNING",
  DEVICE_CHANGE: "ERROR",
  SUSPICIOUS_ACTIVITY: "ERROR",
} as const;
